// <auto-generated />
using System;
using HCM.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCM.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427170929_AddNewColumns")]
    partial class AddNewColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HCM.Models.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("HCM.Models.Models.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<string>("CadidateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandidateAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandidateGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandidatePhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("InterviewDate")
                        .HasColumnType("date");

                    b.Property<string>("Interviewer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InterviewerDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPreviouslyAttended")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnattended")
                        .HasColumnType("bit");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<bool>("OnboardingRequested")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProfileCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileCreator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillSets")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandidateId");

                    b.HasIndex("JobId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("HCM.Models.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeAge")
                        .HasColumnType("int");

                    b.Property<double>("EmployeeBasic")
                        .HasColumnType("float");

                    b.Property<double>("EmployeeCTC")
                        .HasColumnType("float");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EmployeeDob")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeManager")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmployeeStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<int?>("JobsJobId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isManager")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobsJobId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HCM.Models.Models.Jobs", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JobStatus")
                        .HasColumnType("bit");

                    b.Property<string>("JobStatusDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            JobName = "Software Engineer",
                            JobStatus = true,
                            JobStatusDescription = "Open"
                        },
                        new
                        {
                            JobId = 2,
                            JobName = "Data Analyst",
                            JobStatus = true,
                            JobStatusDescription = "Open"
                        },
                        new
                        {
                            JobId = 3,
                            JobName = "Project Manager",
                            JobStatus = false,
                            JobStatusDescription = "Closed"
                        },
                        new
                        {
                            JobId = 4,
                            JobName = "UX Designer",
                            JobStatus = true,
                            JobStatusDescription = "Open"
                        });
                });

            modelBuilder.Entity("HCM.Models.Models.LedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("LedgerEntries");
                });

            modelBuilder.Entity("HCM.Models.Models.Requesites", b =>
                {
                    b.Property<int>("ReqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReqId"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReqDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReqName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReqId");

                    b.ToTable("Requesites");

                    b.HasData(
                        new
                        {
                            ReqId = 1,
                            ReqDescription = "",
                            ReqName = "Assets"
                        },
                        new
                        {
                            ReqId = 2,
                            ReqDescription = "",
                            ReqName = "Department"
                        },
                        new
                        {
                            ReqId = 3,
                            ReqDescription = "",
                            ReqName = "Designation"
                        },
                        new
                        {
                            ReqId = 4,
                            ReqDescription = "",
                            ReqName = "Gender"
                        });
                });

            modelBuilder.Entity("HCM.Models.Models.RequisiteDetails", b =>
                {
                    b.Property<int>("RequisiteDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequisiteDetailsId"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReqId")
                        .HasColumnType("int");

                    b.Property<string>("RequisiteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequisiteValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequisiteDetailsId");

                    b.HasIndex("ReqId");

                    b.ToTable("RequisiteDetails");

                    b.HasData(
                        new
                        {
                            RequisiteDetailsId = 1,
                            ReqId = 1,
                            RequisiteValue = "Laptop"
                        },
                        new
                        {
                            RequisiteDetailsId = 2,
                            ReqId = 1,
                            RequisiteValue = "Mouse"
                        },
                        new
                        {
                            RequisiteDetailsId = 3,
                            ReqId = 2,
                            RequisiteValue = "HR"
                        },
                        new
                        {
                            RequisiteDetailsId = 4,
                            ReqId = 2,
                            RequisiteValue = "Finance"
                        },
                        new
                        {
                            RequisiteDetailsId = 5,
                            ReqId = 2,
                            RequisiteValue = "Operations"
                        },
                        new
                        {
                            RequisiteDetailsId = 6,
                            ReqId = 2,
                            RequisiteValue = "Technical"
                        });
                });

            modelBuilder.Entity("HCM.Models.Models.Candidate", b =>
                {
                    b.HasOne("HCM.Models.Models.Jobs", "Jobs")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("HCM.Models.Models.Employee", b =>
                {
                    b.HasOne("HCM.Models.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId");

                    b.HasOne("HCM.Models.Models.Jobs", "Jobs")
                        .WithMany()
                        .HasForeignKey("JobsJobId");

                    b.Navigation("Candidate");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("HCM.Models.Models.LedgerEntry", b =>
                {
                    b.HasOne("HCM.Models.Models.Account", "Account")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("HCM.Models.Models.RequisiteDetails", b =>
                {
                    b.HasOne("HCM.Models.Models.Requesites", "Requesites")
                        .WithMany()
                        .HasForeignKey("ReqId");

                    b.Navigation("Requesites");
                });

            modelBuilder.Entity("HCM.Models.Models.Account", b =>
                {
                    b.Navigation("LedgerEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
